server:
  port: 8082

spring:
  name: java-demo
  datasource:
    name: defaultDataSource
    url: jdbc:mysql://localhost:3306/skin
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    banner-mode: off


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
  global-config:
    banner: false
