spring:
  profiles:
    active: pro

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
  global-config:
    banner: false
  mapper-locations: classpath:**/mapper/xml/*.xml
