spring:
  name: java-demo
  profiles: dev
  datasource:
    name: defaultDataSource
    url: jdbc:mysql://localhost:3306/skin
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    banner-mode: off
  redis:
    database: 0
    host: localhost
    port: 6379
    password: root
    # Redis 链接超时时间(毫秒)
    timeout: 10000
    # 过期时间一个小时
    expireTimeSecond: 3600
    # 缓存时间
    cache-minute: 1
    lettuce:
      pool:
        # 连接池最大链接数（负数代表没有限制）
        max-idle: 16
        # 最大空闲链接
        max-active: 32
        # 最small空闲链接
        min-idle: 8

server:
  port: 8082
  servlet:
    session:
      timeout: 60 # session超时时间为60秒
